export {
  REQORD_DIR,
  CONTEXT_DIR,
  REQUIREMENTS_DIR,
  SPECIFICATIONS_DIR,
  SETTINGS_DIR,
  TEMPLATES_DIR,
  RULES_DIR,
  ASSETS_DIR,
  DOMAIN_DIR,
  ISSUE_TEMPLATES_DIR,
  FEEDBACK_DIR,
  ISSUES_DIR,
} from "./paths.js";
